### ISSUE TITLE
after update from 18.04 to 20.04 the extension is still there but no showing in the TOP menu

### ISSUE THREAD

**Issue by petr-hybler** [martin31821/cpupower#118]
Hello, I have just recently updated to 20.04 from 18.04 and the extension is still there but I cannot seem to get it to the TOP bar

![Screenshot from 2020-04-22 12-31-36](https://user-images.githubusercontent.com/17429498/79940811-576d5d00-8495-11ea-98b3-d9a1c1763d05.png)
![Screenshot from 2020-04-22 12-32-43](https://user-images.githubusercontent.com/17429498/79940822-605e2e80-8495-11ea-92af-5f693ac5972a.png)

I can't even seem to find it in the software center 

![Screenshot from 2020-04-22 12-33-33](https://user-images.githubusercontent.com/17429498/79940878-88e62880-8495-11ea-8fee-0efca81a0b61.png)

OS Model: Ubuntu 20.04 LTS (x64)
CPU Model: Intel® Core™ i7-8565U CPU @ 1.80GHz × 8 
Gnome: 3.36.1
Kernel: Linux version 5.4.0-26-generic (buildd@lcy01-amd64-029) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))
policyKit: pkaction version 0.105

**Comment by fin-ger** [comment]
Can you please run

```
journalctl -f
```

and toggle the extension off and on again?

Please paste the output of the above command here. Make sure, no confidential information is included in the output, like passwords, names, location, etc.

Regarding the software center, you can try to reinstall the extension over the [extensions website](https://extensions.gnome.org/extension/945/cpu-power-manager/).

**Comment by fin-ger** [comment]
Oh, and I forgot to mention. For Ubuntu 20.04 it __might__ be necessary to install the [`gnome-shell-extensions`](https://packages.ubuntu.com/focal/gnome-shell-extensions) package from the [`universe`](https://help.ubuntu.com/community/Repositories/Ubuntu) repository.

**Comment by petr-hybler** [comment]
I already have the gnome-shell-extensions ... 

the output of this command is as follows: 

`Apr 22 16:15:39 lcf gnome-shell[1892]: JS ERROR: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
                                       CPUFreqProfileButton@/home/petr/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/profilebutton.js:37:9
                                       createMenu@/home/petr/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js:134:33
                                       CPUFreqIndicator@/home/petr/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js:83:14
                                       enable/</<@/home/petr/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/extension.js:73:34
                                       spawn_process_check_exit_code/<@/home/petr/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/utils.js:50:13
Apr 22 16:15:39 lcf gnome-shell[1892]: Could not create transient scope for PID 47141: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 47141 does not exist.
`
I only inserted the error that occurred .. if you want the whole log, let me know .. I can paste it

**Comment by fin-ger** [comment]
This looks like the issue fixed in be89b51. Are you able to update/reinstall the extension via the website?

**Comment by petr-hybler** [comment]
sorry am a bit struggling here .. I downloaded 3.36/20 ... but dunno how to "update" ?

**Comment by fin-ger** [comment]
![image](https://user-images.githubusercontent.com/5300274/79959521-83341700-8484-11ea-830c-206ac625931d.png)

The extensions website should include a green update button (I'm on the latest version, so no update available). It should not be necessary to download the update manually.

**Comment by petr-hybler** [comment]
not for me either :( 
![Screenshot from 2020-04-22 16-33-50](https://user-images.githubusercontent.com/17429498/79959764-16864000-84b7-11ea-996b-bd40f176c07d.png)

plus when I tried "sudo make install install-tool" it returned this:

`Compiling schemas...
Updating translations...
./scripts/update-translations.sh: line 9: /usr/bin/msgfmt: No such file or directory
make: *** [Makefile:14: build] Error 127
`

**Comment by fin-ger** [comment]
It is not necessary to build the extension yourself. As you are currently running the extension as a user installation, I would recommend not installing it system wide now. The extension website says you need to install a browser extension in order to manage your extensions here. Please do so. The website will then be able to manage your extensions and update accordingly. I can't tell why the Software Center is not capable of this.

**Comment by petr-hybler** [comment]
I need browser extension to manage it in the system??

**Comment by fin-ger** [comment]
Yes, or you can use the `Gnome Web` Browser, which has this functionality included.

**Comment by petr-hybler** [comment]
still nothing in the top panel ... how can I uninstall this? I will try to remove and install again

**Comment by petr-hybler** [comment]
I even managed to uninstall via the website and extension .. and install again .. but still nothing .. same error in journalctl ...

any idea?

**Comment by fin-ger** [comment]
To clarify: Using the extensions website for updating/installing/managing gnome-shell extensions is the default for all gnome extensions. The Software Center can also be used for extension updates/management, but as gnome-shell-extensions are not fully supported under 20.04 yet, this is not working.

The full uninstallation got implemented in version 9.0.0, you seem to have a pre 9.0.0 version. After you updated the extension on the website with the green button, you should be able to migrate your installation to the v9 version.

If this is not working, you can try to forcefully remove it by running

```
rm -r ~/.local/share/gnome-shell/extensions/cpupower@mko-sl.de
```

Now log out and back in again.

**Comment by petr-hybler** [comment]
fantastic :) it's fixed !!!

![Screenshot from 2020-04-22 17-02-11](https://user-images.githubusercontent.com/17429498/79962766-10925e00-84bb-11ea-8e2e-7f9c6d3eeea6.png)

**Comment by fin-ger** [comment]
I'm sorry that the Ubuntu Software Center is not working for extension management. You may report this to the Ubuntu devs, as I cannot do anything about it but advise you to avoid the Software Center for extension management :(

**Comment by petr-hybler** [comment]
nvm.. I know it's not your fault ... thx a lot for your time and help :) I am happy to have this awesome extension :) thank you !!!
