### ISSUE TITLE
Installation doubts

### ISSUE THREAD

**Issue by marcioAlmada** [martin31821/cpupower#12]
> If you get the same value as above, everything is working and you can proceed to the next step.

What's the next step? I did all steps, installed the extension and couldn't see any new icon in my toolbar. My model seems compatible:
```
$ ls /sys/devices/system/cpu/intel_pstate/
max_perf_pct  min_perf_pct  no_turbo

**Comment by fin-ger** [comment]
Have you installed the extension itself via the gnome extensions website or manually?

**Comment by marcioAlmada** [comment]
Via website. Then followed the wiki steps.

**Comment by martin31821** [comment]
First you should get the extension from Github, as the latest (important changes) are not yet on extensions.gnome.org, so either you wait some days or you just clone the repository. 
Then you should be able to use the extension (it is possible that you need to restart gnome, press Alt+F2, type r, enter).

**Comment by marcioAlmada** [comment]
Still no dice here:

![captura de tela de 2015-06-23 18 31 44](https://cloud.githubusercontent.com/assets/227395/8317776/38ccd2f6-19d6-11e5-8d0b-7574d774428e.png)

Unfortunately, no errors messages are logged.

**Comment by martin31821** [comment]
As of V2, the installation is much simpler and more intuitive. 
If you install the extension via the gnome website it will check if everything is setup correctly and if not, it will generate all neccessary files and show you instructions how and where to copy them. 

If this doesn't help, I updated the instructions in the wiki.

**Comment by marcioAlmada** [comment]
Removed everything and installed again. No success. The main difference is that now I can't see the extension "settings" button. Looking glass shows no error.

**Comment by martin31821** [comment]
please check also the related issues #11 and #15,
You can try the latest git version for the fix.
