### ISSUE TITLE
Text invisible on theme change

### ISSUE THREAD

**Issue by cosmin-craciun** [martin31821/cpupower#121]
Only issue is a visual bug.The Maximum Frequency, Minimum Frequency and Current Frequency text becomes invisible on changing shell theme from default one.

Default theme (Pop):

![1 _Default_Theme](https://user-images.githubusercontent.com/64773781/80963473-aa410000-8e17-11ea-9930-435ae5912466.png)

Custom theme (Vimix):

![2_Custom_Theme](https://user-images.githubusercontent.com/64773781/80963476-ac0ac380-8e17-11ea-87a6-00b66d077d34.png)

Pop!_OS 20.04

GNOME Shell 3.36.1 with pop-shell extension enabled

**Comment by fin-ger** [comment]
As you pointed out: this is not a bug in this extensions. Please report it to the theme authors.
