### ISSUE TITLE
Turning off turbo mode intel i7950h

### ISSUE THREAD

**Issue by Apogeum12** [martin31821/cpupower#123]
Ubuntu 20.04 on 19.10 this same
kernel 5.4.0-31-generic on 5.4.0-26 this same
Installed in system tlp, and intel-undervolt
Lenovo Legion y540

If I return from Battery mode to quiet mode or performane mode etc.(AC power ofcourse)  then turbo mode the turn off(in setting as enabled), Even when I try to enabled it manualy.
When I run for example fish benchmark(WebGL Aquarium) in browser.   Turbo mode is off, he not change automatic for a long time. After 30-60 secunds  turbo  mode something it turn on but return to off  if i exit the benchmark.  So my notebook work on (1.5-2.6 Ghz)  in  quiet mode but should (1.5-2.8  Ghz)  2.6  GHz is base frequencies.

When i reboot my computer on AC power they it all work ok. So it is problem when switch from BAT power  to AC power for the quiet,  power etc. mode with running  turbo mode.

Intel-Undervolt in my opinion don't do conflict
/etc/Intel-undervolt.conf

```sh
# Enable or Disable Triggers (elogind)
# Usage: enable [yes/no]

enable no

# CPU Undervolting
# Usage: undervolt ${index} ${display_name} ${undervolt_value}
# Example: undervolt 2 'CPU Cache' -25.84

undervolt 0 'CPU' -148.44
undervolt 1 'GPU' -79.10
undervolt 2 'CPU Cache' -148.44
undervolt 3 'System Agent' -89.84
undervolt 4 'Analog I/O' -38.09

# Power Limits Alteration
# Usage: power ${domain} ${short_power_value} ${long_power_value}
# Power value: ${power}[/${time_window}][:enabled][:disabled]
# Domains: package
# Example: power package 45 35
# Example: power package 45/0.002 35/28
# power package 100/0.010:enabled 62/28.00:enabled

# Critical Temperature Offset Alteration
# Usage: tjoffset ${temperature_offset}
tjoffset -16

# Energy Versus Performance Preference Switch
# Usage: hwphint ${mode} ${algorithm} ${load_hint} ${normal_hint}
# Hints: see energy_performance_available_preferences
# Modes: switch, force
# Load algorithm: load:${capture}:${threshold}
# Power algorithm: power[:${domain}:[gt/lt]:${value}[:[and/or]]...]
# Capture: single, multi
# Threshold: CPU usage threshold
# Domain: RAPL power domain, check with `intel-undervolt measure`
# Example: hwphint force load:single:0.8 performance balance_performance
# Example: hwphint switch power:core:gt:8 performance balance_performance
# hwphint switch load:multi:0.925 balance_power power

# Daemon Update Interval
# Usage: interval ${interval_in_milliseconds}

interval 3000

# Daemon Actions
# Usage: daemon action[:option...]
# Actions: undervolt, power, tjoffset
# Options: once

daemon undervolt:once
daemon power
daemon tjoffset
```

**Comment by fin-ger** [comment]
Have you configured Auto-Switch in CPU Power Manager?

![image](https://user-images.githubusercontent.com/5300274/83041762-20b0d680-a041-11ea-837c-e4e0a8b2e116.png)

Your Auto-Switch profiles may have Turbo Boost configured, and will change your Turbo Boost setting when switching from e.g. battery to AC. You can turn Auto-Switch off in the CPU Power Manager menu to prevent profile switching.

> When I run for example fish benchmark(WebGL Aquarium) in browser. Turbo mode is off, he not change automatic for a long time. After 30-60 secunds turbo mode something it turn on but return to off if i exit the benchmark.

This behavior is not created by CPU Power Manager. This extension will only reset a manually set Turbo Boost setting directly after switching from AC to battery or vice versa. After that you can re-enable or disable Turbo Boost in the extension menu. If this is not working, it's an issue outside of this extension.

**Comment by Apogeum12** [comment]
You have right, thank for your answerr. When I changed in setting tlp
PCIE_ASPM_ON_AC= powersave  --> performance 
and
CPU_SCALING_GOVERNOR_ON_AC= powersave -> performance
and without changing
CPU_ENERGY_PERF_POLICY_ON_AC="balance_performance"
In add I deleted from system package "irqbalance"
but I don't sure done this help some in this issue.
Now turbo mode enable more faster.
