### ISSUE TITLE
Upgradeable for Gnome 3.36.3

### ISSUE THREAD

**Issue by xzj8b3** [martin31821/cpupower#126]
It should be as updated given after the update to Gnome 3.36.03 no longer seems to maintain settings

**Comment by AQZ0216** [comment]
occur ERROR on Gnome 3.36.3

**Comment by martin31821** [comment]
Which distribution are you using?

**Comment by AQZ0216** [comment]
Sorry, after I restart my computer, it's work~
Perhaps it's because I just upgrade to Ubuntu 20.04.
Thx

**Comment by fin-ger** [comment]
@xzj8b3 Is this still an issue?

**Comment by xzj8b3** [comment]
> @xzj8b3 Is this still an issue?

I am by now to 3.38 with Fedora, but I believe that I signaled it is little updated!
