### ISSUE TITLE
Is there a way of using the functionality of this extension in an env other than Gnome?

### ISSUE THREAD

**Issue by lolero** [martin31821/cpupower#128]
There is a [post](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1873083/comments/34) that claims that this tool can solve [this](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1873083) bug, which I am experiencing on a Linux Mint 19 machine.

Is there a way I could set the 'turbo' option off without running the Gnome env?

Thanks! :D

**Comment by mastercaution** [comment]
This is a Gnome Shell extension. So if you want to use all its features, you have to run it in a Gnome environment.

But if I get it right, you just want to disable the turbo of your CPU and there are two simple ways of doing so without Gnome:

1. Run the Bash script of this extension `tool/cpufreqctl` as root: `sudo ./cpufreqctl turbo 0`
(more help: `./cpufreqctl turbo` or `./cpufreqctl --help`)
2. Or set the p-state setting yourself (as root): `echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo`
(The Bash script is doing exactly the same)

For both you don't need to install the extension with its installer ... just run the script or the command ;)
You can find even more information about Intel P-State [here](https://www.kernel.org/doc/Documentation/cpu-freq/intel-pstate.txt).

**Comment by lolero** [comment]
Thank you!
