### ISSUE TITLE
'Attempt Installation' doesn't respond.

### ISSUE THREAD

**Issue by ojasiiitd** [martin31821/cpupower#134]
Hi, I installed this extension a few days ago from **extensions.gnome.org**.
I was able to get the tray icon in my panel but when I click on 'Attempt Installation' option (which the README says is to _enter your root password to install a policy kit rule_), nothing happens.

<img src="https://user-images.githubusercontent.com/43749506/93017756-c5ebbc80-f5e8-11ea-97a6-cff88d63b582.jpeg" width="300" height="300" />

So I am unable to use this extension at all. It'd be great to have some suggestions or maybe I need to downgrade to a lower version of the extension. TIA.

System info:
- Ubuntu 18.04.5 LTS x86_64
- GNOME 3.28.4
- CPU Power Manager 9.0.2

**Comment by mastercaution** [comment]
Sorry for all this waiting!
Is there something interesting in your system logs? I don't know what could cause this issue and I couldn't reproduce it on a very similar system but maybe the logs can help ;)
