### ISSUE TITLE
[QUESTION] What is auto switch?

### ISSUE THREAD

**Issue by dodalovic** [martin31821/cpupower#146]
Hi, your tool really helps a lot! Thank you for that!

Just one question, though: what's the purpose of **Auto Switch** option?

Thanks!

**Comment by mastercaution** [comment]
Hi, the Auto Switch option enables the feature of automatically selecting your profile according to the power status of your computer (on battery or charging). In the preferences you can select which profile you want for each of the two states. If "Auto Switch" is enabled, then the extension will automatically switch to the according profile if you plug in or unplug your device from a wall adapter.

**Comment by dodalovic** [comment]
Wonderful, thank you for the clarification!
