### ISSUE TITLE
Add support for governor

### ISSUE THREAD

**Issue by mmdmine** [martin31821/cpupower#147]
Please add support for setting cpu governor.
My current cpu has two governors: performance and powersave.
with this extension, it's always on powersave, and I should set it to performance manually using `# cpupower frequency-set -g performance`.

**Comment by fin-ger** [comment]
Duplicate of #68

**Comment by mmdmine** [comment]
Ok sorry

**Comment by fin-ger** [comment]
no problem :smile:
