### ISSUE TITLE
Feature request: profiles shortcuts

### ISSUE THREAD

**Issue by Seybo** [martin31821/cpupower#154]
Would be nice to be able to have shortcuts to profiles or/and to be able to control it from the command line (i have no idea if it's possible).

Use case example for the feature: some people don't always keep their laptops on AC even if they have it around to save their laptop's battery lifespan. They discharge the battery to 40% or something like this, then charge to 80%, then discharge to 40%, and so on. In this case, even though the system is running on battery it's not needed to powersave and it would be handy to be able to quickly change the profile to "Performance" every time AC was plugged of.

**Comment by fin-ger** [comment]
This is what `Auto Switch` is for. You can configure your `Default battery profile` to `Performance`. However, keep in mind that some BIOS's decrease your base clock or disable `Turbo Boost` automatically when no AC adapter is connected. This extension can't change anything when this is happening. You might look into your BIOS settings if you experience this issue.
