### ISSUE TITLE
Doesn't work on gnome 40.4.0

### ISSUE THREAD

**Issue by Neo-29** [martin31821/cpupower#159]
Not compatible with latest version on archlinux

**Comment by fin-ger** [comment]
See #151

**Comment by Neo-29** [comment]
Was working until a few days

This 151 is irrelevant or you have to tell me where the information is given.
It Was working

**Comment by fin-ger** [comment]
It cannot work in Gnome 40. Gnome 40 is not supported, yet. PR #151 tracks the progress for Gnome 40 support.

**Comment by Neo-29** [comment]
.... Can you tell me how I made it work on gnome 40 so?
I read this thread

Last post july...so
Nevermind

**Comment by peter-kehl** [comment]
Related/duplicate of #174.
