### ISSUE TITLE
Support Gnome 3.18

### ISSUE THREAD

**Issue by martin31821** [martin31821/cpupower#19]

**Comment by wfpaisa** [comment]
please

**Comment by martin31821** [comment]
I can't support 3.18 right now, as I am stuck to 3.16, so it will take some weeks I think.

**Comment by frol** [comment]
@martin31821 Have you updated the extension on Gnome Extensions site? It doesn't allow to install this extension from there and says that it is unsupported.

**Comment by martin31821** [comment]
No not yet. I want to fix #18 for the next release

**Comment by martin31821** [comment]
Just updated on Gnome Extensions site, should be available in the next few days!

**Comment by frol** [comment]
@martin31821 Great! Thank you!
