### ISSUE TITLE
Doesn't the polkit action allow running any command as root ?

### ISSUE THREAD

**Issue by miguel-negrao** [martin31821/cpupower#20]
Correct if I'm wrong, but you polkit action authorizes running a script owned by the normal user without any authorization. A malicious agent which gains access to the computer (but does not know the root password) can edit that script, effectively being able to run any command. Perhaps I'm missing something ? Shouldn't you make the script only writable by root ?

**Comment by martin31821** [comment]
I think you are right.
I will add a warning/notification in the install instructions to chown the file.
