### ISSUE TITLE
Logout not required for installation

### ISSUE THREAD

**Issue by alanmcg** [martin31821/cpupower#204]
The install guide for non listed os's (install from zip) states:

"Now log out and back in again. Yes, this is really necessary thanks to Gnome. After logging back in, enable the extension with:"

This is not actually the case, you can just type alt + f2 to get the run dialog and then type "r" + enter to reload gnome, without being logged out. I just tested it and it works

**Comment by fin-ger** [comment]
Sorry if this sounds harsh. But yes, it is strictly required for any modern OS using Wayland.
