### ISSUE TITLE
It seems not having effect on battery mode

### ISSUE THREAD

**Issue by lviggiani** [martin31821/cpupower#23]
Hi, on my ivybridge laptop, whatever setting I change (min freq, max freq, turbo ecc) the cpu frequency won't go beyond 800MHz even in high load (my CPU max freq is 2.5GHz).

**Comment by martin31821** [comment]
Can you provide more information?
Especially:
* Exact CPU Model
* Exact Notebook model
* OS
* Kernel Version

Please also double check that your BIOS allows you to control the cpu frequency when in battery mode and verify that you installed everything correctly.
