### ISSUE TITLE
Show active choosen profile

### ISSUE THREAD

**Issue by xdajog** [martin31821/cpupower#24]
#### Request for enhancement

It would be very nice if one could see which profile is currently selected (maybe a simple check mark on the last selected profile or so)

**Comment by martin31821** [comment]
How can I handle the case if the user selects a profile and changes any setting afterwards?
Just show the last set profile or don't highlight any profile at all?

**Comment by xdajog** [comment]
For me this would be clear enough and logical:

if the user changes the sliders (I think that is what you meant) then it shouldn't highlight any profile at all. The reason behind is that it **is** actually **no** profile anymore. When the user wants to use those settings again he/she should save a new profile for this..

**Comment by martin31821** [comment]
I created a sample implementation for testing purposes.
I think it will go into the next release.

**Comment by xdajog** [comment]
Looks really great !! Thanks for implementing!
