### ISSUE TITLE
cpupower extension doesn't work

### ISSUE THREAD

**Issue by dcharlespyle** [martin31821/cpupower#26]
It displays the frequency, but it won't change the frequency.  When it tries to change the frequency, I have to enter the password four times (once for each core), but then nothing changes.  Running any one of the following in terminal does, however, work on all cores:

sudo cpupower frequency-set -g powersave
sudo cpupower frequency-set -g conservative
sudo cpupower frequency-set -g ondemand
sudo cpupower frequency-set -g performance

All installation instructions were followed to the letter and the newest from GIT is installed.  The names of governors in the list in preferences also do not match the names of those actually installed.

Running pkexec ~/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/cpufreqctl max 100 gives the following error:

/home/XXXXXX/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/cpufreqctl: line 47: /sys/devices/system/cpu/intel_pstate/max_perf_pct: No such file or directory

This is on a system running Fedora 23 Workstation, GNOME Shell 3.18.4.  Processor is Intel(R) Core(TM)2 Quad CPU    Q9650  @ 3.00GHz

**Comment by martin31821** [comment]
Your CPU is not supported by pstate (only Core i Series)
So you can't use this extension.
