### ISSUE TITLE
Frequency Does Not Change 

### ISSUE THREAD

**Issue by dsreyes1014** [martin31821/cpupower#28]
After switching between profiles for the cpu frequencies the frequency number does not change.

**Comment by martin31821** [comment]
Can you provide more information?

Which CPU model, which gnome version, which extension version etc.
Please also include logs (journald, extension log etc.)

**Comment by dsreyes1014** [comment]
I'm running an i5 4570t Haswell cpu on Gentoo Linux kernel 4.5.1, Gnome 3.18 not sure about extension version as there's no version number that comes with it so I'm assuming latest git through extensions.gnome.org.

**Comment by martin31821** [comment]
Your CPU is supported, Gnome 3.18 should work as well.

Can you try to set the frequency manually using the pstate files and cpufreqctl?
please take a look at #6 and #17 as this seems to be related.

make sure your policykit action is working correctly [https://github.com/martin31821/cpupower/wiki/Installation](Wiki Installation)

**Comment by dsreyes1014** [comment]
the link to cpupower is a dead link.  I'll try it manually and see if it works.

**Comment by martin31821** [comment]
Oops, got the wrong order in markdown. Fixed it.

**Comment by dsreyes1014** [comment]
Hey martin after seeing #17 I noticed I didn't compile intel pstate driver in my kernel build.  Very sorry I missed.  It's working now as it should it seems and all is well.
