### ISSUE TITLE
Previously Selected Profile Isn't Shown To Be Selected After Reopening

### ISSUE THREAD

**Issue by dsreyes1014** [martin31821/cpupower#30]
I'm losing the bullet point next to the profile.  I'm noticing that the bullet point when selecting a profile is missing after reopening the extension from the top bar.  So it's a little tough to remember which profile I'm on after awhile.  I'm on Gnome 3.18 Gentoo kernel 4.5.2.

**Comment by martin31821** [comment]
The bullet is shown when the settings (min, max, turbo boost) match the settings of any profile.

I suppose this only happens when on profile quiet or energy saver? 
If so, it's a problem with your minimum frequency (see #25)

**Comment by dsreyes1014** [comment]
Ahh you're right.  I setup the profiles to match my lowest frequency and it stays on when reopening.  Thanks for Martin!!!
