### ISSUE TITLE
Authentication required when multiple users use CPU Power Manager

### ISSUE THREAD

**Issue by thomaskr** [martin31821/cpupower#34]
The installation guide advises to copy the policy file from the users extension installation folder to `/usr/share/polkit-1/actions/`. The file contains a reference to the `cpufreqctl` binary in the users extension folder. The policy will apply to this binary only.

When a second user on the same system installs the extension and follows the installation procedure, the policy is overwritten by the version of the new user which point to his local version of `cpufreqctl`.

A the result the first user has to authenticate now on any change. Applying a profile may require multiple authentications.

I fixed the problem locally by copying the binary to `/usr/local/bin/`, setting `cpufreqctl_path` accordingly and changing `<annotate key="org.freedesktop.policykit.exec.path">` in the policy file.

**Comment by martin31821** [comment]
That's the way it was intended to use with multiple users. 
I think the way to go is to introduce a configuration option to change the cpufreqctl_path to something like /usr/local/bin or /opt/bin or ... 

You can also install the extension as system-wide extension, to /usr/share/gnome-shell/extensions, which should also solve the problem.
