### ISSUE TITLE
Blank name results in error in overview

### ISSUE THREAD

**Issue by dnivi3** [martin31821/cpupower#37]
Everything works correctly, but I accidentally added an entry without a blank name. This resulted in an error in which metadata information about the package is displayed instead of the name of the mode. Please see the attached screenshot. 

![screenshot from 2016-09-26 12-36-14](https://cloud.githubusercontent.com/assets/1163576/18831563/a7df0c6a-83e6-11e6-8c97-4cf5fe1d4686.png)

**Comment by martin31821** [comment]
Got it reproduced, I will look into it.

**Comment by dnivi3** [comment]
Thanks for fixing this! I didn't realise I actually had an empty item in the list, so I didn't think of that I could delete it. 

As a thank, do you happen to have a Bitcoin-address I can send a coffee to?

**Comment by martin31821** [comment]
Please send me an email, my address can be found in my profile.
