### ISSUE TITLE
Latest update is botched

### ISSUE THREAD

**Issue by Vistaus** [martin31821/cpupower#38]
This extension was working fine on my Arch Linux with GNOME 3.22 but today's extension update from the GNOME Extensions website results in a complete hang of the entire system and I have to manually rm the extension folder from a tty to have a working system again. Going back to the previous version of this extension resolves the issue for me.

Could you please fix this?

(btw, someone on 3.20 also reported this issue on the GNOME Extensions website so I'm not the only one)

**Comment by martin31821** [comment]
I'll look into it tomorrow, I think I need to setup an ubuntu to reproduce this, it is related to glib.

**Comment by Vistaus** [comment]
Are you still looking into this? 'Cause I miss this extension! :cry: Btw, I'm using Arch, not Ubuntu.

**Comment by fin-ger** [comment]
How can I install the v7 tagged version without extensions.gnome.org but with a git checkout? I have a gentoo running and can test multiple configurations of glib. I will try to debug the issue.

**Comment by martin31821** [comment]
I haven't been able to reproduce this on a bunch of distros (Ubuntu Gnome, Arch, Gentoo, Fedora)

You could try and delete the whole extension installation folder, i.e. do a clean install to prevent update problems.

**Comment by Vistaus** [comment]
Tried that already when I submitted this issue but it didn't work. But it does work now. The only problem is that, after installing and restarting Shell, it says "Installation required" even though I've followed all of the instructions (copying the cpufreq file and changing permissions and stuff).

**Comment by martin31821** [comment]
The file which is used to determine if the installation was successful is `.pgen` in the extension directory.
So running `touch $EXTENSIONDIR/.pgen` should do the job.

**Comment by Vistaus** [comment]
Thanks. Got a little further now but it's still not working yet 'cause when I click "High Performance" it's asking for my sudo password but it doesn't accept it. My sudo password works fine elsewhere, for example in a terminal window.

What to do now?

**Comment by martin31821** [comment]
Can you post the contents of your `mko.cpupower.policy` file here?
Please also check if the cpufreqctl executable matches the path of `mko.cpupower.policy`

**Comment by martin31821** [comment]
@Vistaus FYI I have done a clean install yesterday on arch (just git clone and follow the installation instructions) and it worked like a charm. I'm using Archlinux on an i7-6820HK, so I'm closing this for now. Feel free to open a new ticket when the issue persists.
