### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by martin31821** [martin31821/cpupower#39]
@MarPiRK
@honza-kasik 
May I bother you to add some translations I recently introduced?
For german and english I added them myself.

**Comment by honza-kasik** [comment]
@martin31821 Sure! I try to look at it today!

**Comment by honza-kasik** [comment]
New strings added in #40

**Comment by martin31821** [comment]
Would you mind translating the changed strings for the new settings dialog?

**Comment by MarekPikula** [comment]
Sure, will look into that.
