### ISSUE TITLE
policy-kit installation wrong?!

### ISSUE THREAD

**Issue by steadfasterX** [martin31821/cpupower#43]
In my case the following happened:

I installed the extension over extensions.gnome.org
Then after the extension gets enabled gnome asks multiple times for my password to execute _cpufreqctl_

The policy file gets installed correctly into:
_/usr/share/polkit-1/actions/mko.cpupower.policy_

but within that file I find the line:

`<annotate key="org.freedesktop.policykit.exec.path">/home/tfi/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/cpufreqctl</annotate>`

which is either not correct or the installer missed to moved the cpufreqctl file from the directory src/.

I "fixed" it by modifying the path to:
`<annotate key="org.freedesktop.policykit.exec.path">/home/tfi/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/cpufreqctl</annotate>`

**Comment by steadfasterX** [comment]
btw: `/usr/share/polkit-1/actions/mko.cpupower.setcpufreq.policy` contains the path to **src/**

**Comment by martin31821** [comment]
this could be indeed a leftover from a previous version.
I will adapt the installer to remove old versions of the policy file...

**Comment by Oliph** [comment]
I add the same issue and the solution given here solve the issue for me.

**Comment by superkartoffel** [comment]
I can confirm this issues. I also had a second policy, probably from a previous version and got ask to enter a password multiple times on each login and whenever I tried to use the extension.
Removing the second policy resolved the issue for me.

**Comment by eode** [comment]
Still broken.  Still the same issue.  Two polkit files, the older being `mko.cpupower.policy`, the newer being `mko.cpupower.setcpufreq.policy`.  Deleting the older one fixes the issue.

**Comment by fin-ger** [comment]
This is being worked in in #107
