### ISSUE TITLE
Option to not restore last setting

### ISSUE THREAD

**Issue by biji** [martin31821/cpupower#44]
In my case before suspending , I use high performance profile on AC, then after resuming my system, I use slower cpu setting, set by TLP, but cpupower set it back to high profile. Please add option to not restoring last setting

Thanks

**Comment by martin31821** [comment]
Good point, will implement this.

**Comment by levinit** [comment]
support this proposal.Now I use ['cpupower'](https://wiki.archlinux.org/index.php/CPU_frequency_scaling#cpupower)to keep turbo boost off,but it is not convenient for using.

**Comment by tonylambiris** [comment]
@martin31821 I can take a crack at this -- I like the idea I just need any pointers/quick-starts regarding how to build out more UI elements. I tried Builder and Glide but I didn't see any intuitive hints in the UI.

What app/IDE do you use for creating widgets and binding actions? And also if you can kick me a few curated bookmarks you deemed save-worthy please kick em my way (everything I've been reading isn't what I want or it's super out of date).

**Comment by mastercaution** [comment]
> In my case before suspending , I use high performance profile on AC, then after resuming my system, I use slower cpu setting, set by TLP, but cpupower set it back to high profile.

This is exactly why I implemented #96. Now TLP don't need to touch the pstate values anymore instead the extension can handle the AC and battery settings.

> What app/IDE do you use for creating widgets and binding actions?

I used Glade in case you are still interested.

**Comment by fin-ger** [comment]
@biji is this issue fixed?

**Comment by fin-ger** [comment]
If this is still an issue, please reopen!
