### ISSUE TITLE
Uninstall helper proram

### ISSUE THREAD

**Issue by ruffson** [martin31821/cpupower#48]
On Fedora 26, how can I uninstall whatever helper I installed from within the extension?

Thank you in advance.

**Comment by martin31821** [comment]
There is only one file installed by this extension, you have to remove it manually: 
```sh
sudo rm /usr/share/polkit-1/actions/mko.cpupower.setcpufreq.policy
```

All other programs and files are remved by the gnome tools.

**Comment by ruffson** [comment]
Great, thank you!
