### ISSUE TITLE
Not throttling since kernel 4.13.x on Fedora 

### ISSUE THREAD

**Issue by mgrobelin** [martin31821/cpupower#56]
Thank you for this great extension!

I just wanted to share, that throttling suddenly stopped to work on my device around a month ago, obviously since Fedora 26/27 updated their kernel packages to 4.13.x. 

Since I downgraded to [4.12.12 kernel packages](https://koji.fedoraproject.org/koji/buildinfo?buildID=969045) the extension behaves fine again.

I found this [Reddit post](https://www.reddit.com/r/archlinux/comments/6zgxcb/kernel_4131_cpu_doesnt_downclock_anymore/) and some [kernel Git notes](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=51204e0639c49ada02fd823782ad673b6326d748):

> Linux 4.13 doesn't show the current frequency in `/proc/cpuinfo` anymore [...] 

So maybe similar code as https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/404/files would do?

**Comment by martin31821** [comment]
This was fixed in the latest version, see #50 for reference.
