### ISSUE TITLE
Feature suggestion: Complete uninstallation

### ISSUE THREAD

**Issue by jebeld17** [martin31821/cpupower#58]
Please add a 'Completely Uninstall' option to the CPU Power Manager applet that completely reverses any changes the applet may have done to the user's computer including remove and reverse the scripts installed by the applet to work properly.

This gives users peace of mind that in case the applet does not work for their needs, they can still reverse any changes, more than likely, that may have incurred.

**Comment by GXGOW** [comment]
According to #48, you only have to remove one file. It would be helpful to put that in the README though.

**Comment by martin31821** [comment]
I'll put it in the readme.

**Comment by jebeld17** [comment]
What about to undo the changes?

**Comment by kiview** [comment]
I assume it would be reset after restart, not sure though?

**Comment by micklynch** [comment]
Can anyone confirm how do, and what happens if, I uninstall?

**Comment by martin31821** [comment]
pstate is resetted after every boot to full frequency range and enabled turbo boost.

**Comment by digiberk** [comment]
> Can anyone confirm how do, and what happens if, I uninstall?

@micklynch Simply uninstall the extension from extensions.gnome.org and reboot. I can confirm that upon rebooting, my CPU governor was set back to normal.

**Comment by fin-ger** [comment]
This is being worked on in #107
