### ISSUE TITLE
Remove dropdown indicator to reduce footprint

### ISSUE THREAD

**Issue by freiform** [martin31821/cpupower#59]
it would be nice to be able to hide the arrow beside the actual icon to reduce the extension's footprint.

**Comment by fin-ger** [comment]
This is specific to your gnome shell theme and must not be handled by the extension itself.

**Comment by freiform** [comment]
What is the mechanism in other extensions that do not show it, e.g.
"Extensions"?

2018-04-14 10:58 GMT+02:00 Fin Christensen <notifications@github.com>:

**Comment by fin-ger** [comment]
Hmm, I don't know. But I would consider it an anti-pattern to change this as this leads to several extensions behaving differently although they are doing the same when clicking on the icon.
