### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by steelbrain** [martin31821/cpupower#6]
Gnome Shell 3.16
Processor: Intel® Core™ i5-4200U CPU @ 1.60GHz × 4 
Graphics: Intel® Haswell Mobile
intel_pstate enabled in kernel

and by not working, I meant that the current frequency is stuck at 0mhz

**Comment by fin-ger** [comment]
Have you followed the [installation](https://github.com/martin31821/cpupower/wiki/Installation) instructions? At the moment this extension does not work out of the box. You need to configure your policy kit and install cpufreqctl in your `$PATH`.

**Comment by steelbrain** [comment]
Well, it was not mentioned in the GNOME Extensions page. Gonna try it now.

**Comment by steelbrain** [comment]
:heart: It works

**Comment by fin-ger** [comment]
Yes that's right. I will tell the maintainer to add this to the extension page (currently talking with him ^^).
