### ISSUE TITLE
extension fails to start

### ISSUE THREAD

**Issue by swaroophangal** [martin31821/cpupower#63]
Hello,

Tried to install it from extension.gnome.org as well as extracting the zip from github to extensions folder and running the policy installation script. I get the following error for preferences in tweakui and extension does not start.

**************************
Gtk.BuilderError: /home/swaroop/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/data/cpupower-preferences.glade:75:1 <object> requires attribute "id"

Stack trace:
  CPUPowerPreferences<._init@/home/swaroop/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/preferences.js:56
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
  buildPrefsWidget@/home/swaroop/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/prefs.js:41
  Application<._selectExtension@/usr/share/gnome-shell/js/extensionPrefs/main.js:102
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._extensionSelected@/usr/share/gnome-shell/js/extensionPrefs/main.js:121
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@/usr/share/gnome-shell/js/extensionPrefs/main.js:112
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._extensionsLoaded@/usr/share/gnome-shell/js/extensionPrefs/main.js:221
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  _emit@resource:///org/gnome/gjs/modules/signals.js:124
  ExtensionFinder<._extensionsLoaded@/usr/share/gnome-shell/js/misc/extensionUtils.js:178
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  done@/usr/share/gnome-shell/js/misc/fileUtils.js:33
  _collectFromDirectoryAsync/</<@/usr/share/gnome-shell/js/misc/fileUtils.js:51
  onNextFileComplete@/usr/share/gnome-shell/js/misc/fileUtils.js:21
  main@/usr/share/gnome-shell/js/extensionPrefs/main.js:278
  @<command line>:1
  **********************************

Ran the following diagnostics:
cmd: "gnome-shell --version"
result: "GNOME Shell 3.10.4"

cmd: "grep -i pstate /boot/config-$(uname -r)"
result: "CONFIG_X86_INTEL_PSTATE=y"

cmd: "sudo ./installer.sh install"
result : "Installing policykit action... Success
               Fixing permissions... Success"

cmd: "sudo ./installer.sh check"
result: "Installed"

cmd: "./cpufreqctl min get" (similar for turbo and max)
result: "./cpufreqctl: line 206: /sys/devices/system/cpu/intel_pstate/min_perf_pct: No such file or directory"

CPU model: "Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz"

Linux kernel: "Linux MAVLAB5 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"

policykit version: 0.105-4ubuntu3.14.04.1

**Comment by martin31821** [comment]
Your log indicates that your system does not support pstate. result: 
`./cpufreqctl: line 206: /sys/devices/system/cpu/intel_pstate/min_perf_pct: No such file or directory`

Which means that this extension won't work for you, your kernel is too old.
