### ISSUE TITLE
Broken on Gnome 3.32

### ISSUE THREAD

**Issue by Sangeppato** [martin31821/cpupower#74]
Currently the extension doesn't appear in the top panel in Gnome 3.32, other extensions have similar problems so it could be about some Gnome changes.

**Comment by martin31821** [comment]
I'm not yet on 3.32 but I'm going to look into it as soon as I can update.

**Comment by martin31821** [comment]
Started to work on it: https://github.com/martin31821/cpupower/tree/fix/3.32
Seems like a bigger change...

**Comment by martin31821** [comment]
If you like, you can check out the 3.32 branch and do some testing.
I think, we also might need to change the minimum supported versions from 3.10 to 3.30ish, because there are big changesdue to the introduction of ES6 classes.

**Comment by K5HV** [comment]
fix/3.32 seems to be working with 3.32, at least for me.
Thank you!

**Comment by Sangeppato** [comment]
Working here as well, thank you very much!
I've just noticed two small issues:

* The dot to indicate the currently used profile is not displayed
* If I set a very low minimum frequency, the slider is not reset to the actual hardware minimum frequency as it used to do (It can even stay at 0%)

**Comment by martin31821** [comment]
> * The dot to indicate the currently used profile is not displayed

Fixed in 4da44c2

> * If I set a very low minimum frequency, the slider is not reset to the actual hardware minimum frequency as it used to do (It can even stay at 0%)

That's kernel dependent. It seems that with 5.0 the frequency is not reset anymore.

**Comment by martin31821** [comment]
Update is available on extensions.gnome.org, so fixed now.
