### ISSUE TITLE
Show current cpu freq in top bar

### ISSUE THREAD

**Issue by technixp** [martin31821/cpupower#8]
It would be very nice to have checkbox for this option.

**Comment by martin31821** [comment]
With this option enabled you could get serious log spam into your `auth.log`, as policykit logs every invoke of the cpufreqctl utility. I don't know how to prevent this yet, if I can figure this out, I could add a switch for this.

**Comment by technixp** [comment]
What do you think about this approach?
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/master/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L1348

**Comment by martin31821** [comment]
Nice approach, I tested it and it seemed to work, so I will add this to the next version, therefore you won't get any spam to your `auth.log` even if the extensions menu is open. 
This will be configurable.

**Comment by technixp** [comment]
Thanks :)
