### ISSUE TITLE
installer.sh doesn't work on ostree (Silverblue)

### ISSUE THREAD

**Issue by dac73** [martin31821/cpupower#83]
Installer.sh fails on Fedora Silverblue:
```
 ~/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/installer.sh  install
Installing policykit action... /home/drumpf/.local/share/gnome-shell/extensions/cpupower@mko-sl.de/src/installer.sh: line 56: /usr/share/polkit-1/actions/mko.cpupower.setcpufreq.policy: Read-only file system
Failed
```
* Please include the following information (only for bugreports):
  * CPU Model: `i7 5500u`
  * Linux kernel version: `5.2.5-200.fc30.x86_64`
  * Gnome shell version: `3.32`
  * OS: Fedora Silverblue 30

**Comment by serverwentdown** [comment]
I believe there is no solution to running cpupower in Silverblue, because it currently relies on the existence of a shell script and a PolicyKit action. Creating a PolicyKit action will require a package to be installed, but that makes this extension dependent on the distribution.

**Comment by fin-ger** [comment]
I will add instructions for package maintainers to the README when #95 is done. You can then package and install this extension via the package manager of your distribution.

**Comment by fin-ger** [comment]
#107 got merged into master, which adds instructions to the README for package maintainers.

**Comment by fin-ger** [comment]
As v9.0.0 got released, packaging for Silverblue could start. As am not using Fedora Silverblue, nor have I any experience packaging for Silverblue, I am asking for help here. Anyone interested in packaging?

**Comment by fin-ger** [comment]
As Fedora Silverblue is focused on Flatpak and the Flatpak developers noted that [supporting installation of Gnome Shell Extensions is out-of-scope](https://github.com/flatpak/flatpak/issues/481), I will label this issue as `wontfix` until a solution pops up for installing Gnome Shell Extensions via Flatpak.

Please reopen if you know of such a solution.
