### ISSUE TITLE
Add option for decimal places

### ISSUE THREAD

**Issue by win98se** [martin31821/cpupower#91]
Since a version update (long ago), now the frequency displays with 3 decimal places (e.g. `2196.478 MHz`) instead of integer (e.g. `2196 MHz`).

I recommend the developer(s) to add an option so that people can customize how many decimal places they want for the frequency indicator.

**Comment by fin-ger** [comment]
I think sane defaults would suffice. I suggest 2 decimal places for GHz, and no decimal places for MHz.

**Comment by fin-ger** [comment]
Update got reviewed and released.
