### ISSUE TITLE
Installation not working in Solus Gnome

### ISSUE THREAD

**Issue by Juno-Girl** [martin31821/cpupower#94]
The issue persists through a reboot. It has worked on all other distros I've used it on. 
Video: https://youtu.be/Q2wq-9mP5k8

**Comment by Juno-Girl** [comment]
Sorry for the poor video quality by the way. I have no idea what I'm doing in Kdenlive.

**Comment by fin-ger** [comment]
A new installation method is currently in the making in #107, maybe this fixes your issue?

**Comment by fin-ger** [comment]
Can you try again with the new version?

**Comment by monterrr** [comment]
Doesn't install for me when it asks the cpufreqctl, nor does it work manually on the cmd, I'm on fedora silverblue 32 
I used version 20 for gnome 3.36

**Comment by fin-ger** [comment]
If this is still an issue, please reopen.
